"""empty message

Revision ID: 1d68b0bb1901
Revises: 80566b7ee03d
Create Date: 2025-03-08 13:30:40.094021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d68b0bb1901'
down_revision = '80566b7ee03d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_product', sa.Date(), nullable=True))
        batch_op.drop_column('date_roduct')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_roduct', sa.DATE(), nullable=True))
        batch_op.drop_column('date_product')

    # ### end Alembic commands ###
