"""empty message

Revision ID: 1f793bc4cabb
Revises: f2fe22dd763a
Create Date: 2025-02-25 21:12:01.789846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f793bc4cabb'
down_revision = 'f2fe22dd763a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manualbook',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=True),
    sa.Column('fk_item', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fk_item'], ['item.id'], name=op.f('fk_manualbook_fk_item_item'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_manualbook')),
    sa.UniqueConstraint('slug', name=op.f('uq_manualbook_slug'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('manualbook')
    # ### end Alembic commands ###
