"""empty message

Revision ID: 23c3e2852d2a
Revises: c51afcd654c0
Create Date: 2025-02-26 19:38:06.569233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23c3e2852d2a'
down_revision = 'c51afcd654c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manualbook', schema=None) as batch_op:
        batch_op.drop_column('name_file')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manualbook', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name_file', sa.VARCHAR(length=100), nullable=True))

    # ### end Alembic commands ###
