"""empty message

Revision ID: 3e04445333bd
Revises: a03430729de1
Create Date: 2025-02-25 15:08:17.892203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e04445333bd'
down_revision = 'a03430729de1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        # batch_op.drop_constraint(None, type_='foreignkey')
        # batch_op.drop_constraint(None, type_='foreignkey')
        # batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('fk_ConditionItme')
        batch_op.drop_column('fk_PlaceOperation')
        batch_op.drop_column('fk_TypeEquipment')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fk_TypeEquipment', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('fk_PlaceOperation', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('fk_ConditionItme', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'placeoperation', ['fk_PlaceOperation'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'typeequipment', ['fk_TypeEquipment'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'conditionitme', ['fk_ConditionItme'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###
