"""empty message

Revision ID: 64dfe97d84f5
Revises: 
Create Date: 2025-02-16 21:34:10.419054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64dfe97d84f5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conditionitme',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conditionitme'))
    )
    op.create_table('manufactureritme',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_manufactureritme'))
    )
    op.create_table('placeoperation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_placeoperation'))
    )
    op.create_table('statusitme',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_statusitme'))
    )
    op.create_table('typeequipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_typeequipment'))
    )
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('exploitation', sa.Date(), nullable=True),
    sa.Column('fk_ManufacturerItme', sa.Integer(), nullable=False),
    sa.Column('fk_StatusItme', sa.Integer(), nullable=False),
    sa.Column('fk_ConditionItme', sa.Integer(), nullable=False),
    sa.Column('fk_TypeEquipment', sa.Integer(), nullable=False),
    sa.Column('fk_PlaceOperation', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fk_ConditionItme'], ['conditionitme.id'], name=op.f('fk_item_fk_ConditionItme_conditionitme')),
    sa.ForeignKeyConstraint(['fk_ManufacturerItme'], ['manufactureritme.id'], name=op.f('fk_item_fk_ManufacturerItme_manufactureritme')),
    sa.ForeignKeyConstraint(['fk_PlaceOperation'], ['placeoperation.id'], name=op.f('fk_item_fk_PlaceOperation_placeoperation')),
    sa.ForeignKeyConstraint(['fk_StatusItme'], ['statusitme.id'], name=op.f('fk_item_fk_StatusItme_statusitme')),
    sa.ForeignKeyConstraint(['fk_TypeEquipment'], ['typeequipment.id'], name=op.f('fk_item_fk_TypeEquipment_typeequipment')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_item'))
    )
    op.create_table('modelitme',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('fk_ModelItme', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fk_ModelItme'], ['manufactureritme.id'], name=op.f('fk_modelitme_fk_ModelItme_manufactureritme')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_modelitme'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('modelitme')
    op.drop_table('item')
    op.drop_table('typeequipment')
    op.drop_table('statusitme')
    op.drop_table('placeoperation')
    op.drop_table('manufactureritme')
    op.drop_table('conditionitme')
    # ### end Alembic commands ###
