"""empty message

Revision ID: 7d499bbe6648
Revises: c0d43b43b293
Create Date: 2025-02-25 01:14:05.940737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d499bbe6648'
down_revision = 'c0d43b43b293'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.alter_column('fk_ModelItme',
               existing_type=sa.INTEGER(),
               nullable=True)
        # batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_item_fk_ModelItme_modelitme'), 'modelitme', ['fk_ModelItme'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_item_fk_ModelItme_modelitme'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'modelitme', ['fk_ModelItme'], ['id'])
        batch_op.alter_column('fk_ModelItme',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
