"""empty message

Revision ID: 80566b7ee03d
Revises: 5f3df074c223
Create Date: 2025-03-08 13:16:29.927169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80566b7ee03d'
down_revision = '5f3df074c223'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('serial_num', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('warranty', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('date_roduct', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_column('date_roduct')
        batch_op.drop_column('warranty')
        batch_op.drop_column('serial_num')

    # ### end Alembic commands ###
