"""empty message

Revision ID: 864ea25d3aca
Revises: c0075c7c64e7
Create Date: 2025-02-27 03:17:28.138292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '864ea25d3aca'
down_revision = 'c0075c7c64e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('check_work', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenance', schema=None) as batch_op:
        batch_op.drop_column('check_work')

    # ### end Alembic commands ###
