"""empty message

Revision ID: a03430729de1
Revises: 7d499bbe6648
Create Date: 2025-02-25 15:06:52.898736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a03430729de1'
down_revision = '7d499bbe6648'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        # batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('fk_StatusItme')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fk_StatusItme', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'statusitme', ['fk_StatusItme'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###
