"""empty message

Revision ID: c0075c7c64e7
Revises: 23c3e2852d2a
Create Date: 2025-02-27 03:11:55.046988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0075c7c64e7'
down_revision = '23c3e2852d2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regulatorywork',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_regulatorywork'))
    )
    op.create_table('schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('period', sa.String(length=7), nullable=True),
    sa.Column('date_time', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_schedules'))
    )
    op.create_table('maintenance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('data_time', sa.Date(), nullable=True),
    sa.Column('fk_schedule', sa.Integer(), nullable=False),
    sa.Column('fk_regulatory_work', sa.Integer(), nullable=False),
    sa.Column('fk_item', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fk_item'], ['item.id'], name=op.f('fk_maintenance_fk_item_item')),
    sa.ForeignKeyConstraint(['fk_regulatory_work'], ['regulatorywork.id'], name=op.f('fk_maintenance_fk_regulatory_work_regulatorywork'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['fk_schedule'], ['schedules.id'], name=op.f('fk_maintenance_fk_schedule_schedules'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_maintenance'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('maintenance')
    op.drop_table('schedules')
    op.drop_table('regulatorywork')
    # ### end Alembic commands ###
