"""empty message

Revision ID: c0d43b43b293
Revises: 64dfe97d84f5
Create Date: 2025-02-24 01:59:53.596347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0d43b43b293'
down_revision = '64dfe97d84f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fk_ModelItme', sa.Integer(), nullable=False))
        # batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_item_fk_ModelItme_modelitme'), 'modelitme', ['fk_ModelItme'], ['id'])
        batch_op.drop_column('fk_ManufacturerItme')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fk_ManufacturerItme', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_item_fk_ModelItme_modelitme'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'manufactureritme', ['fk_ManufacturerItme'], ['id'])
        batch_op.drop_column('fk_ModelItme')

    # ### end Alembic commands ###
