"""empty message

Revision ID: c51afcd654c0
Revises: 1f793bc4cabb
Create Date: 2025-02-26 19:26:37.726265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c51afcd654c0'
down_revision = '1f793bc4cabb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manualbook', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name_file', sa.String(length=100), nullable=True))
        batch_op.alter_column('slug',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=30),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manualbook', schema=None) as batch_op:
        batch_op.alter_column('slug',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.drop_column('name_file')

    # ### end Alembic commands ###
