"""empty message

Revision ID: c75e030cde18
Revises: 3e04445333bd
Create Date: 2025-02-25 15:09:20.689974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c75e030cde18'
down_revision = '3e04445333bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fk_StatusItme', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('fk_ConditionItme', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('fk_TypeEquipment', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('fk_PlaceOperation', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_item_fk_TypeEquipment_typeequipment'), 'typeequipment', ['fk_TypeEquipment'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('fk_item_fk_StatusItme_statusitme'), 'statusitme', ['fk_StatusItme'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('fk_item_fk_ConditionItme_conditionitme'), 'conditionitme', ['fk_ConditionItme'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('fk_item_fk_PlaceOperation_placeoperation'), 'placeoperation', ['fk_PlaceOperation'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_item_fk_PlaceOperation_placeoperation'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_item_fk_ConditionItme_conditionitme'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_item_fk_StatusItme_statusitme'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_item_fk_TypeEquipment_typeequipment'), type_='foreignkey')
        batch_op.drop_column('fk_PlaceOperation')
        batch_op.drop_column('fk_TypeEquipment')
        batch_op.drop_column('fk_ConditionItme')
        batch_op.drop_column('fk_StatusItme')

    # ### end Alembic commands ###
