"""empty message

Revision ID: f2fe22dd763a
Revises: c75e030cde18
Create Date: 2025-02-25 20:48:52.851771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2fe22dd763a'
down_revision = 'c75e030cde18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notepad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('fk_item', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fk_item'], ['item.id'], name=op.f('fk_notepad_fk_item_item'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notepad')),
    sa.UniqueConstraint('fk_item', name=op.f('uq_notepad_fk_item'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notepad')
    # ### end Alembic commands ###
